Repository thoth-station/s2i-tensorflow-notebook, pull requests merged in 2020-10, with the labels that each got.

#5 Automatic update of dependency bokeh from 2.1.1 to 2.2.3
  Pipfile.lock
Labels: approved, bot, size/XL

#6 Automatic update of dependency dask from 2.22.0 to 2.30.0
  Pipfile.lock
Labels: approved, bot, size/XL

#8 Automatic update of dependency distributed from 2.22.0 to 2.30.0
  Pipfile.lock
Labels: approved, bot, size/XS

#11 Automatic update of dependency plotly from 4.9.0 to 4.12.0
  Pipfile.lock
Labels: approved, bot, size/XS

#14 Automatic update of dependency pyarrow from 1.0.0 to 2.0.0
  Pipfile.lock
Labels: approved, bot

#18 Automatic update of dependency s3fs from 0.4.2 to 0.5.1
  Pipfile.lock
Labels: approved, bot, size/M

#23 Automatic update of dependency scikit-learn from 0.23.1 to 0.23.2
  Pipfile.lock
Labels: approved, bot, size/L

#29 Automatic update of dependency scipy from 1.4.1 to 1.5.3
  Pipfile.lock
Labels: approved, bot, size/L

#47 Automatic update of dependency seaborn from 0.10.1 to 0.11.0
  Pipfile.lock
Labels: approved, bot, size/XS

#52 Automatic update of dependency tensorflow from 2.3.0 to 2.3.1
  Pipfile.lock
Labels: approved, bot, size/S

#64 updated README.md
  README.md
Labels: approved, size/M
